const donors = [
  {
    id: 1,
    name: "Rahim Ahmed",
    bloodGroup: "A+",
    city: "Chattogram",
    area: "Agrabad",
    phone: "01812345678",
    available: true,
  },
  {
    id: 2,
    name: "Nusrat Jahan",
    bloodGroup: "O-",
    city: "Chattogram",
    area: "GEC Circle",
    phone: "01798765432",
    available: false,
  },
  {
    id: 3,
    name: "Tanvir Hasan",
    bloodGroup: "B+",
    city: "Dhaka",
    area: "Dhanmondi",
    phone: "01945678901",
    available: true,
  },
  {
    id: 4,
    name: "Farzana Akter",
    bloodGroup: "AB+",
    city: "Sylhet",
    area: "Zindabazar",
    phone: "01612349876",
    available: true,
  },
  {
    id: 5,
    name: "Sabbir Hossain",
    bloodGroup: "A-",
    city: "Khulna",
    area: "Sonadanga",
    phone: "01556789012",
    available: false,
  },
  {
    id: 6,
    name: "Mehedi Hasan",
    bloodGroup: "O+",
    city: "Rajshahi",
    area: "Shaheb Bazar",
    phone: "01899887766",
    available: true,
  },
  {
    id: 7,
    name: "Shamima Sultana",
    bloodGroup: "B-",
    city: "Barisal",
    area: "Nathullabad",
    phone: "01722334455",
    available: true,
  },
  {
    id: 8,
    name: "Arif Hossain",
    bloodGroup: "AB-",
    city: "Cumilla",
    area: "Kotbari",
    phone: "01933445566",
    available: true,
  },
];

export default donors;